language: python
python:
  - "3.4"

# command to install dependencies, e.g. pip install -r requirements.txt 
install: 
  - pip install Flask
  - pip install coverage coveralls

# command to run tests, e.g. python setup.py test
script:  
  - python -m unittest discover -v

# post to slack
notifications:
  slack: storjcommunity:TZfUO9ycY8R9UYwztWZTo0jk
  email: false

# display coverage
after_success:
    coveralls